package com.muhammadfarhan.profilmahasiswa.ui.theme

import androidx.compose.ui.graphics.Color

internal val LightPrimary = Color(0xFF1F4E79)
internal val LightOnPrimary = Color(0xFFFFFFFF)
internal val LightPrimaryContainer = Color(0xFFD6E4F0)
internal val LightOnPrimaryContainer = Color(0xFF0B1F33)
internal val LightSecondary = Color(0xFF326B65)
internal val LightOnSecondary = Color(0xFFFFFFFF)
internal val LightSecondaryContainer = Color(0xFFBCECE4)
internal val LightOnSecondaryContainer = Color(0xFF0B211E)
internal val LightBackground = Color(0xFFF7F9FC)
internal val LightOnBackground = Color(0xFF191C1E)
internal val LightSurface = Color(0xFFFFFFFF)
internal val LightOnSurface = Color(0xFF191C1E)
internal val LightSurfaceVariant = Color(0xFFE1E7EC)
internal val LightOnSurfaceVariant = Color(0xFF41474D)
internal val LightOutline = Color(0xFF71787F)
internal val LightError = Color(0xFFBA1A1A)
internal val LightOnError = Color(0xFFFFFFFF)

internal val DarkPrimary = Color(0xFFA5C8EC)
internal val DarkOnPrimary = Color(0xFF003258)
internal val DarkPrimaryContainer = Color(0xFF154A70)
internal val DarkOnPrimaryContainer = Color(0xFFD1E4FF)
internal val DarkSecondary = Color(0xFFA0D4CC)
internal val DarkOnSecondary = Color(0xFF003733)
internal val DarkSecondaryContainer = Color(0xFF164E49)
internal val DarkOnSecondaryContainer = Color(0xFFBCECE4)
internal val DarkBackground = Color(0xFF111417)
internal val DarkOnBackground = Color(0xFFE1E2E5)
internal val DarkSurface = Color(0xFF111417)
internal val DarkOnSurface = Color(0xFFE1E2E5)
internal val DarkSurfaceVariant = Color(0xFF41484D)
internal val DarkOnSurfaceVariant = Color(0xFFC1C7CE)
internal val DarkOutline = Color(0xFF8B9198)
internal val DarkError = Color(0xFFFFB4AB)
internal val DarkOnError = Color(0xFF690005)
